### ISSUE TITLE
AWS: Unable to find available subscriptions for all your installed products

### ISSUE THREAD

**Issue by mcedica** [openshift/openshift-ansible-contrib#210]
This is more a question than an issue:
Is this supposed to work with a '30 Day Self-Supported Red Hat OpenShift Container Platform, 2-Core Evaluation' subscription? 
 ./ose-on-aws.py  always fails with the message: Unable to find available subscriptions for all your installed products. Is this because I don't have the right subscription?

fatal: [ose-app-node02.io.nuxeo.com]: FAILED! => {"changed": false, "cmd": "subscription-manager subscribe", "failed": true, "msg": "", "rc": 1, "stderr": "", "stdout": "\n\nInstalled Product Current Status:\nProduct Name: Red Hat Enterprise Linux Server\nStatus:       Not Subscribed\n\nUnable to find available subscriptions for all your installed products.\n", "stdout_lines": ["", "", "Installed Product Current Status:", "Product Name: Red Hat Enterprise Linux Server", "Status:       Not Subscribed", "", "Unable to find available subscriptions for all your installed products."]}

Thx!

**Comment by cooktheryan** [comment]
When you run the ose-on-aws.py with that subscription do you have "30 Day Self-Supported Red Hat OpenShift Container Platform, 2-Core Evaluation" quoted?

**Comment by mcedica** [comment]
Hope I get the question right, yes:

Configured values:
	stack_name: openshift-infra
	ami: ami-6f68cf0f
	region: us-west-2
	master_instance_type: m4.large
----
	apps_dns: apps.io.nuxeo.com
	rhsm_user: mcedica
	rhsm_password: *******
	**rhsm_pool: 30 Day Self-Supported Red Hat OpenShift Container Platform, 2-Core Evaluation**
	containerized: False

**Comment by cooktheryan** [comment]
I do believe that you are entering that value correctly. I realize there has been a file changed in regards to subscriptions. Can you make the following change?  The change is putting in ^ at the pool line. pool: "^{{ rhsm_pool }}"

```
vi $git_repo_location/openshift-ansible-contrib/playbooks/roles/rhsm-subscription/tasks/main.yaml
    - name: Register host
      redhat_subscription:
        username: "{{ rhsm_user }}"
        password: "{{ rhsm_password }}"
        state: present
        pool: "^{{ rhsm_pool }}"
```

Once that change is made re-run the ose-on-aws.py I have added this change to PR #211
