### ISSUE TITLE
Unable to install Openshift  Origin (containerised) it requires version or image?

### ISSUE THREAD

**Issue by sensiblemedia** [openshift/openshift-ansible-contrib#320]
Hi,

I am attempting to install Openshift Origin (containerised) but receive a message that a version or image is required.
As yet I have been unable to find the location or the resolution to this issue.

**Executing the follow command:**
`$ ./ose-on-aws.py --stack-name=dev --deployment-type=origin --public-hosted-zone=****.co.uk --keypair=OSE-key --create-key=yes --key-path=/home/centos/.ssh/id_rsa.pub --github-client-secret=4****e  --github-organization=openshift --github-organization=me-openshift --github-client-id=f****a --ami=ami-1daa8c7b --containerized=true --region=eu-west-1`

**Get the following response after sometime:**
```
TASK [openshift_version : fail] ************************************************
fatal: [ose-master03.motabtest.co.uk]: FAILED! => {"changed": false, "failed": true, "msg": "Must specify openshift_release or openshift_image_tag in inventory to install origin. (suggestion: add openshift_release=\"1.2\" to inventory)"}

```

**Look like the above error is from:**
```
/usr/share/ansible/openshift-ansible/playbooks/common/openshift-cluster/roles/openshift_version/tasks

# Block attempts to install origin without specifying some kind of version information.
# This is because the latest tags for origin are usually alpha builds, which should not
# be used by default. Users must indicate what they want.
- fail:
    msg: "Must specify openshift_release or openshift_image_tag in inventory to install origin. (suggestion: add openshift_release=\"1.2\" to inventory)"
  when:
  - is_containerized | bool
  - openshift.common.deployment_type == 'origin'
  - openshift_release is not defined
  - openshift_image_tag is not defined
```
Thanks, 
SRG
