### ISSUE TITLE
hawkular-metrics not working in GCP deployment

### ISSUE THREAD

**Issue by bdurrow** [openshift/openshift-ansible-contrib#446]
From a recent master with some patches to support CentOS/Origin.  I set these in config.yaml
```
openshift_hosted_metrics_deploy: true
openshift_hosted_metrics_storage_volume_size: 20Gi
```

Deployment seemed to go fine but when log into the console there is a banner (toast?) about a problem with metrics.  Digging deeper I find there are two pods that are not starting correctly due to problems with arguments.

Logs for openshift-infra/ hawkular-metrics shows:
```
2017-06-08 17:49:45 Starting Hawkular Metrics
unable to write 'random state'
unable to write 'random state'
The --truststore_authorities value is not specified. Aborting
```
Logs for openshift-infra/hawkular-cassandra shows:
`The --truststore_node_authorities value is not specified. Aborting`

```
  containers:
    - name: hawkular-metrics
      image: 'docker.io/openshift/origin-metrics-hawkular-metrics:latest'
      command:
        - /opt/hawkular/scripts/hawkular-metrics-wrapper.sh
        - '-b'
        - 0.0.0.0
        - '-Dhawkular.metrics.cassandra.nodes=hawkular-cassandra'
        - '-Dhawkular.metrics.cassandra.use-ssl'
        - '-Dhawkular.metrics.openshift.auth-methods=openshift-oauth,htpasswd'
        - >-
          -Dhawkular.metrics.openshift.htpasswd-file=/secrets/hawkular-metrics.htpasswd.file
        - >-
          -Dhawkular.metrics.allowed-cors-access-control-allow-headers=authorization
        - '-Dhawkular.metrics.default-ttl=7'
        - '-Dhawkular.metrics.admin-tenant=_hawkular_admin'
        - '-Dhawkular-alerts.cassandra-nodes=hawkular-cassandra'
        - '-Dhawkular-alerts.cassandra-use-ssl'
        - '-Dhawkular.alerts.openshift.auth-methods=openshift-oauth,htpasswd'
        - >-
          -Dhawkular.alerts.openshift.htpasswd-file=/secrets/hawkular-metrics.htpasswd.file
        - >-
          -Dhawkular.alerts.allowed-cors-access-control-allow-headers=authorization
        - '-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true'
        - '-Dorg.apache.catalina.connector.CoyoteAdapter.ALLOW_BACKSLASH=true'
        - '-Dcom.datastax.driver.FORCE_NIO=true'
        - '-DKUBERNETES_MASTER_URL=https://kubernetes.default.svc.cluster.local'
        - '-DUSER_WRITE_ACCESS=False'
        - '--hmw.keystore=/secrets/hawkular-metrics.keystore'
        - '--hmw.truststore=/secrets/hawkular-metrics.truststore'
        - >-
          --hmw.keystore_password_file=/secrets/hawkular-metrics.keystore.password
        - >-
          --hmw.truststore_password_file=/secrets/hawkular-metrics.truststore.password
        - '--hmw.jgroups_keystore=/secrets/hawkular-metrics.jgroups.keystore'
        - >-
          --hmw.jgroups_keystore_password_file=/secrets/hawkular-metrics.jgroups.keystore.password
        - '--hmw.jgroups_alias_file=/secrets/hawkular-metrics.jgroups.alias'
```
