### ISSUE TITLE
Support for ca_cert

### ISSUE THREAD

**Issue by ioggstream** [openshift/openshift-ansible-contrib#705]
# FEATURE REQUEST INFO:

Install ca_cert on all nodes included bastion.
Backport this ooo feature: https://github.com/redhat-openstack/openshift-on-openstack#openstack-with-ssltls

## **Problem Description**

The proposed feature enables communication with custom CA certificates sites (eg. openstack api url).

Use Case:

 - the openstack api url is served via an internal CA

## **Proposed Change**

- add a ca_cert parameter, like https://github.com/redhat-openstack/openshift-on-openstack#openstack-with-ssltls

### *Security Impact*

allows interaction non globally certified sites

### *Other End User Impact*

Updating ca_cert should be done with care or the sites w

### *Documentation Impact*

Document 

 - the ca_cert param like https://github.com/redhat-openstack/openshift-on-openstack#openstack-with-ssltls
 - the update procedure

## **Implementation**

Add the ca_cert parameter to the playbook and NOT in CloudConfig or updating ca_certs won't work.

Then do something like

```
- name: Upload or update the ca_cert to all host
  copy: 
    dest: /etc/pki/ca-trust/source/anchors/ocp-ca.crt
    content: |
       {{ca_cert}}
    mode: 0600

- name: update ca trust
  shell: |
     update-ca-trust
     update-ca-trust extract

```

## **References**
See
https://github.com/redhat-openstack/openshift-on-openstack#openstack-with-ssltls
