### ISSUE TITLE
how to disable configure docker-storage-setup in roles/docker-storage-setup

### ISSUE THREAD

**Issue by gouyang** [openshift/openshift-ansible-contrib#959]
If I have docker storage configured previously, how to skip configure it again in `roles/docker-storage-setup`?

I tried to put `docker_storage` into `openshift_disable_check`, but it still replace file `/etc/sysconfig/docker-storage-setup` and cause docker failed to start.

line in inventory: 
`openshift_disable_check=memory_availability,disk_availability,docker_image_availability,docker_storage`

**Comment by cooktheryan** [comment]
@gouyang which provider are you deploying on?

**Comment by gouyang** [comment]
I'm deploying it on CentOS via project `https://github.com/kubevirt/kubevirt-ansible`.

I added a line to skip the step like below, do you think it's reasonable to do it.

```
- block:
    - name: create the docker-storage-setup devicemapper config file for CentOS
      template:
        src: "{{ role_path }}/templates/docker-storage-setup-dm.j2"
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644

  # TODO(shadower): Find out which CentOS version supports overlayfs2
  when: 
    - ansible_distribution == "CentOS"
    - "'docker_storage' not in openshift_disable_check"
```

I've configured the docker storage and it works already. 
```
# cat /etc/sysconfig/docker-storage-setup 
VG="docker-vol"
```
After the playbooks is executed, docker is failed to start because the file content is overwritten.
```
# cat /etc/sysconfig/docker-storage-setup 
DEVS="/dev/sdb"
VG="docker-vol"
DATA_SIZE="95%VG"
STORAGE_DRIVER=overlay2
CONTAINER_ROOT_LV_NAME="dockerlv"
CONTAINER_ROOT_LV_MOUNT_PATH="/var/lib/docker"
CONTAINER_ROOT_LV_SIZE=100%FREE
```

Try to remove lines in `roles/docker-storage-setup/defaults/main.yaml`, then it throws error like `docker_dev` undefined, so I don't want to modify this file.
