### ISSUE TITLE
RHV provider: install ovirt-guest-agent-common in the VMs

### ISSUE THREAD

**Issue by mykaul** [openshift/openshift-ansible-contrib#969]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one):
BUG REPORT

# BUG REPORT INFO

### Environment

- **Cloud provider**:  
RHV
- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  
CentOS 7.4
- **Version of Ansible** (`ansible --version`):  
2.4.3.0
- **Version of Jinja** (`pip freeze | grep -i jinja`):  

- **Version of Shade** (`pip freeze | grep -i shade`):  

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  
OpenStack? This is OpenShift....

58cc875

**Copy of inventory files and custom variables used (please omit your secrets!)**:  

**Command used to invoke ansible**:  

**Output of ansible run**:  

**Anything else do we need to know**:  
Need to install ovirt-guest-agent into provisioned VMs, so they'll report the IP. Something like:
```
install_guest_agent_script: |
  yum_repos:
    centos-ovirt42:
      baseurl: http://mirror.centos.orig/centos/7/virt/x86_64/ovirt-4.2
      enabled: true
      gpgcheck: false   <--- fix this at some point!
    packages:
    - ovirt-guest-agent-common
    runcmd:
    - systemctl enable ovirt-guest-agent
    - systemctl start ovirt-guest-agent


And then in the cloud init part:
custom_script: "{{ install_guest_agent_script }}"
```

CC 
@cwilkers
