### ISSUE TITLE
 AttachVolume Attach failed. The disk were provisionned in different zone than the node.

### ISSUE THREAD

**Issue by jihed** [openshift/openshift-ansible-contrib#978]
Is this a **BUG REPORT** or a **FEATURE REQUEST** ? (choose one):

# BUG REPORT INFO

### Environment

- **GCP**:  

- **OS details** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):  
Linux 3.10.0-693.17.1.el7.x86_64 x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)

- **Version of Ansible** (`ansible --version`):  
ansible 2.4.2.0

- **The openstack-ansible-contrib version (commit)** (`git rev-parse --short HEAD`):  
003bf3b

### Issue

I deployed a ocp cluster version 3.7 on gcp (3masters, 2infra, 3 apps nodes) on the same project id. The deployment is a multizone ( each master on zone).
When, I create a pvc dynamicly using storageclass, the provisioner was able to create/attach the pvc/pv and the related disk to the node.
```
oc export sc standard-xfs -o yaml:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  name: sd-xfs
parameters:
  type: pd-standard
  fsType: xfs
provisioner: kubernetes.io/gce-pd
```

I decided to upscale the cluster to add one more infra node and one more apps.

The PV provisioning is not working as expected.
error message: 
```
 AttachVolume.Attach failed for volume "pvc-b498355b-2d2f-11e8-b74c-42010a84000a" : GCE persistent disk not found: diskName="kubernetes-dynamic-pvc-b498355b-2d2f-11e8-b74c-42010a84000a" zone="europe-west1-b" 
```
The disk was created in zone different from the zone where the node is hosted.

I update the storageclass configuration to add the zones flag : 
 ```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  name: sd-xfs
parameters:
  type: pd-standard
  fsType: xfs
  zones: europe-west1-d, europe-west1-b, europe-west1-c
provisioner: kubernetes.io/gce-pd
```
Same issue, the pv was created on the europe-west1-d however, the nodes is on  the b zone.

Do we have to create storageclass per zone ?
 Is there any added configuration to push the provisioner to create the pv in the same zone as the node ?
